tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "mas-cli/tap"
cask "osxfuse"
brew "ntfs-3g"
brew "pyenv"
brew "tmux"
brew "yadm"
brew "zsh"
brew "mas-cli/tap/mas"
cask "docker"
cask "font-hack-nerd-font"
cask "iina"
cask "mounty"
cask "visual-studio-code"
mas "LINE", id: 539883307
